spring:
  application:
    name: retrueque
  datasource:
    url: ${DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access: DEBUG
jwt:
  time:
    expiration: ${JWT_EXPIRATION}
  secret:
    key: ${JWT_SECRETKEY}
api:
  base: api/v1