services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend.dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./retrueque:/app
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
